### ISSUE TITLE
OSError: libgomp.so.1 No such file or directory

### ISSUE THREAD

**Issue by briandevvn** [MG-Microsoft/MLOps_Workshop#4]
Follow your Azure MLOps - DevOps for Machine Learning (Part 7)  in Youtube. I have the same code in  Training Model step:
```
az ml run submit-script -g $(azureml.resourceGroup) -w $(azureml.workspaceName) -e $(experiment.name) --ct $(amlcompute.clusterName) -d conda_dependencies.yml -c train_insurance -t ../metadata/run.json train_aml.py
```
But when run the pipeline, the error shows in Training Model step:

```
{
    "error": {
        "code": "UserError",
        "message": "User program failed with OSError: libgomp.so.1: cannot open shared object file: No such file or directory",
        "messageParameters": {},
        "detailsUri": "[https://aka.ms/azureml-run-troubleshooting",](https://aka.ms/azureml-run-troubleshooting%22,)
        "details": []
    },
    "time": "0001-01-01T00:00:00.000Z"
}
```
The base image that chosen automatically by pipeline: mcr.microsoft.com/azureml/o16n-sample-user-base/ubuntu-miniconda

How could I fix that ? I search google, they show that the image need to install libgomp1 by running apt-get install libgomp1.

How could I do that ?

**Comment by briandevvn** [comment]
I found the solution by changing the following work:
1. Change the training/train_insurance.runconfig file:
- Change baseImage to: baseImage: mcr.microsoft.com/azureml/lightgbm-3.2-ubuntu18.04-py37-cpu-inference:latest
2. I also found that your training/conda_dependencies.yml still missing pandas packag, so I add pandas in that file:
- Adding: pandas==1.1.3

**Comment by MG-Cafe** [comment]
Thank you for raising this up! The pull request is merged now.
